services:
  savepoint:
    container_name: web-runtime
    image: felipesms/liga:1.0
    ports:
      - "8080:80"
      - "8081:81"
      - "8082:82"
      - "8083:83"
      - "8084:84"
      - "8085:85"
      - "8086:86"
      - "8087:87"
      - "8088:88"
      - "8089:89"
      - "8090:90"
      - "443:443"
    volumes:
      - ./:/app/
      - ./resources/config/ports.conf:/etc/apache2/ports.conf
      - ./resources/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./resources/config/envvars:/etc/apache2/envvars
      - ./entrypoint.sh:/app/entrypoint.sh
    command: ["bash", "-c", "bash /app/entrypoint.sh && tail -f /dev/null"]
    working_dir: /app/
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: null
      MARIADB_DATABASE: savepoint
      MARIADB_USER: admin
      MARIADB_PASSWORD:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    ports:
      - "3340:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD:
      PMA_ARBITRARY: 1
    ports:
      - "65009:80"
    depends_on:
      - mariadb

volumes:
  mariadb_data:

    