services:
  web-server:
    image: felipesms/liga:1.2
    env_file:
      - .docker-web.env
    ports:
      - "8080:80"
    volumes:
      - ./:/app/
      - ./resources/config/ports.conf:/etc/apache2/ports.conf
      - ./resources/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./resources/config/envvars:/etc/apache2/envvars
      - ./entrypoint.sh:/app/entrypoint.sh
    command: ["bash", "/app/entrypoint.sh"]
    working_dir: /app/
  mariadb:  
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: null
      MARIADB_DATABASE: savepoint
      MARIADB_USER: admin
      MARIADB_PASSWORD:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    ports:
      - "3340:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    profiles: ["laravel"]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD:
      PMA_ARBITRARY: 1
    ports:
      - "65009:80"
    depends_on:
      - mariadb
    profiles: ["laravel"]

volumes:
  mariadb_data:
